SELECT [CustomerKey]
      ,[FirstName]
      ,[LastName]
      ,[BirthDate]
      ,[MaritalStatus]
      ,[Gender]
      ,[EmailAddress]
      ,[YearlyIncome]
      ,[AddressLine1]
      ,[AddressLine2]
      ,[Phone]
      ,[CommuteDistance]
  FROM [AdventureWorksDW2016].[dbo].[DimCustomer]
